services:
  server:
    build: ./server
    env_file: ./server/.env
    command: npm run watch
    ports:
      - "3000:3000"
    networks:
      - backend
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules

  database:
    image: mysql:9.2.0
    env_file: ./.db.env
    networks:
      - backend

networks:
  backend:
    attachable: true

volumes:
  server_node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./server/node_modules
